pipeline {
	agent any
	stages {

		stage('Create Kubernetes Cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'udacity-capstone') {
					sh '''
						eksctl create cluster \
						--name udacitycapstonecluster \
						--managed=false \
						--version 1.14 \
						--nodegroup-name standard-workers \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami=auto \
						--region us-east-1 \
						--zones us-east-1a \
						--zones us-east-1b \
						--zones us-east-1c \
					'''
				}
			}
		}

		stage('Configure kubectl') {
			steps {
				withAWS(region:'us-east-1', credentials:'udacity-capstone') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name udacitycapstonecluster
					'''
				}
			}
		}

	}
}
